import type { Metadata } from 'next'
import { Ubuntu_Mono } from 'next/font/google'
import '../styles/globals.css'
import NavBar from '@/components/NavBar'

const font = Ubuntu_Mono({ subsets: ['latin'], 
                           weight: ['400']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
